definitions:
  User:
    type: object
    properties:
      pk:
        type: integer
        description: primary key
      name:
        type: string
        maxLength: 255
    required:
    - pk
  Group:
    title: Group
    type: object
    properties:
      pk:
        type: integer
        description: primary key
      name:
        type: string
        maxLength: 255
      users:
        type: array
        items:
          $ref: '#/definitions/User'
    required:
    - pk
